// Importiert den Typ Metadata aus dem Next.js-Paket
import type { Metadata } from 'next'
// Importiert die Funktion localFont aus dem Next.js-Paket für lokale Schriftarten
import localFont from 'next/font/local'
import './globals.css'
// Importiert den Providers-Komponenten aus dem angegebenen Pfad
import Providers from '@/components/providers'
import Header from '@/components/header'
import Footer from '@/components/footer'


// Definiert die lokale Schriftart Geist Sans mit den angegebenen Eigenschaften
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// Definiert die RootLayout-Komponente, die das Grundgerüst der Seite darstellt
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode // Definiert das Kind-Element der RootLayout-Komponente
}>) {
  return (
    // Definiert das HTML-Dokument mit der Spracheinstellung und unterdrückt Hydrationswarnungen
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
